config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  get 'index' => 'pages#index'
  get 'home' => 'pages#home'
  get 'profile/:id' => 'pages#profile', as: 'profile'
  get 'explore' => 'pages#explore'
  get 'users', to: 'users#index', as: 'users'
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :posts
  resources :sessions, only: [:new, :create, :destroy]
  resources :users

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user

  mount_uploader :image, ImageUploader

  validates :content,
            presence: true
  validates :user,
            presence: true


end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :posts, dependent: :destroy, foreign_key: 'user_id'

  mount_uploader :profile_image, ImageUploader

  validates :first_name,
            presence: true
  validates :last_name,
            presence: true
  validates :email,
            presence: true,
            uniqueness: true,
            format: {
                with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
            }
  def to_s
    "#{first_name} #{last_name}"
  end

  def self.search(search)
    where('first_name LIKE ? OR last_name LIKE ?', "%#{search}%", "%#{search}%")

  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  private
  def current_user
    User.where(id: session[:user_id]).first
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def home
  end

  def profile
    # Catch the user_id from the URL
    $profile = params[:id]

    # Use the user_id from URL to display the full name of the user on the profile page
    @user_full_name = User.find($profile)

    @post = Post.new

    @posts = Post.where(profile_id: $profile).order(created_at: :desc)

  end

  def explore
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authorize, except: [:show, :index]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.new(post_params)
    @post.profile_id = $profile
    respond_to do |format|
      if @post.save
        format.html { redirect_to :back, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: :back }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to :back, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: :back }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def authorize
    if current_user.nil?
      redirect_to login_url, alert: 'Not authorized! Please log in.'
    else
      if @post && @post.user != current_user
        redirect_to root_path, alert: "Not authorized! Only #{@post.user} has access to this post."
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:content, :image)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    if params[:search]
      @users = User.includes(:posts).search(params[:search])
    else
      @users = User.includes(:posts).all
    end

  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :age, :bio, :email, :profile_image, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_banner.html.erb
<div class="jumbotron">
  <% if current_user %>
      <h1>Welcome to Spacebook</h1>
      <h3>Logged in as <%= current_user.first_name + ' ' + current_user.last_name %></h3>
  <% else %>
      <h1>Welcome to Spacebook</h1>
      <h3>Please sign up or log in</h3>
  <% end %>
</div>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Spacebook</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Home', root_path %></li>
          <%= form_tag users_path, class:'navbar-form navbar-right', method: 'get' do %>
                <%= text_field_tag :search, params[:search], class:"form-control", placeholder: "Search users" %>
                <%= submit_tag 'Search', class:'btn btn-default', name: nil %>
          <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">

          <% if current_user %>
            <li><%= link_to 'My profile', profile_path(id: current_user) %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Settings <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="/account">Account</a></li>
                <li><a href="/privacy">Privacy</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="#">Help</a></li>
              </ul>
            </li>
            <li><%= link_to 'Log Out', logout_path %></li>
          <% else %>
            <li><%= link_to 'Sign Up', signup_path %></li>
            <li><%= link_to 'Log In', login_path %></li>
          <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Socialmedia</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render '/layouts/nav' %>

  <div class="container">
    <%= yield %>
  </div>

</body>
</html>

app/views/pages/explore.html.erb
<h1>Pages#explore</h1>
<p>Find me in app/views/pages/explore.html.erb</p>

app/views/pages/home.html.erb
<%= render '/layouts/banner' %>

app/views/pages/index.html.erb
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>

app/views/pages/profile.html.erb
<div class="row">
  <div class="col-xs-3">
    <div class="panel panel-default fixed-panel panel-transparent">
      <div class="panel-heading">
        <h3 class="panel-title"><%= @user_full_name %></h3>
      </div>
      <div class="panel-body">
        <%= image_tag @user_full_name.profile_image.url, class:'avatar' %>
      </div>
    </div>
  </div>

  <div class="col-xs-6">
    <div class="panel panel-default panel-transparent">
      <div class="panel-heading">
        <h3 class="panel-title">Messages</h3>
      </div>
      <div class="panel-body">
        <% if current_user %>
        <div class="panel panel-default">
          <div class="panel-body">
            <p><%= render 'posts/form' %></p>
          </div>
        </div>
        <% end %>
        <p class="greenText">Spacebook [Version 1.6.5 Alpha]</p>
        <p class="greenText">Copyright 2016 (c) Space Corporation. All rights reserved.</p>
        <br>
        <p class="greenText">C:\users\<%= @user_full_name %>\messages>_</p>
        <br>
        <div class="line"></div>
        <br>
        <% @posts.each do |post| %>
            <p class="greenText"><%= post.content %></p>
            <p class="greenText"><%= image_tag post.image.url, class:'avatar' %></p>
            <p class="greenText">Posted by: <%= link_to post.user, profile_path(id: post.user_id), style: 'color: lime' %></p>
            <p class="greenText"><%= post.created_at %></p>
            <% if current_user %>
                <% if current_user.id == post.user_id or current_user.id == post.profile_id %>
                    <p class="greenText">Options: <%= link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure?' }, style: 'color: lime' %></p>
                <% end %>
            <% end %>
            <br>
            <div class="line"></div>
            <br>
        <% end %>
      </div>
    </div>
  </div>

  <div class="col-xs-3">
    <div class="panel panel-default fixed-panel panel-transparent">
      <div class="panel-heading">
        <h3 class="panel-title">Friends</h3>
      </div>
      <div class="panel-body">
      </div>
    </div>
  </div>
</div>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, 'error') %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <h5>Write a message</h5>
    <br>
    <%= f.text_area :content, class:'form-control' %>
  </div>
  <div class="field form-group">
    <h5>Add image</h5>
    <% if current_user.posts.length > 9 %>
      <%= f.file_field :image, class:'form-control-file' %>
    <% else %>
        <h5>Create <%= 10 - current_user.posts.length %> more posts to be able to add images.</h5>
    <% end %>
  </div>
  <div class="actions">
    <%= f.submit class:'btn btn-primary' %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/users/_form.html.erb
<div class="col-xs-6 col-xs-offset-3">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h1 class="panel-title">Sign Up</h1>
    </div>
    <div class="panel-body">
      <%= form_for(@user) do |f| %>
          <% if @user.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(@user.errors.count, 'error') %> prohibited this user from being saved:</h2>

                <ul>
                  <% @user.errors.full_messages.each do |message| %>
                      <li><%= message %></li>
                  <% end %>
                </ul>
              </div>
          <% end %>

          <div class="field form group">
            <%= f.label :first_name %><br>
            <%= f.text_field :first_name, class:'form-control' %>
          </div>
          <div class="field form group">
            <%= f.label :last_name %><br>
            <%= f.text_field :last_name, class:'form-control' %>
          </div>
          <div class="field form group">
            <%= f.label :age %><br>
            <%= f.number_field :age, class:'form-control' %>
          </div>
          <div class="field form group">
            <%= f.label :bio %><br>
            <%= f.text_area :bio, class:'form-control' %>
          </div>
          <div class="field form group">
            <%= f.label :profile_image %><br>
            <%= f.file_field :profile_image, class:'form-control' %>
          </div>
          <div class="field form group">
            <%= f.label :email %><br>
            <%= f.text_field :email, class:'form-control' %>
          </div>
          <div class="field form group">
            <%= f.label :password %><br>
            <%= f.password_field :password, class:'form-control' %>
          </div>
          <div class="field form group">
            <%= f.label :password_confirmation %><br>
            <%= f.password_field :password_confirmation, class:'form-control' %>
          </div>
          <br>
          <div class="actions">
            <%= f.submit class:'btn btn-primary' %>
          </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', :back %>

app/views/users/index.html.erb
<div class="col-xs-6 col-xs-offset-3">
  <div class="panel panel-default panel-transparent">
    <div class="panel-heading">
      <h3 class="panel-title">Users</h3>
    </div>
    <div class="panel-body">
      <table class="table">
        <thead>
        <tr>
          <th class="greenText">Name</th>
          <th class="greenText">Age</th>
          <th class="greenText">Posts</th>
          <th class="greenText">Ban</th>
          <th colspan="3"></th>
        </tr>
        </thead>

        <tbody>
        <% @users.each do |user| %>
            <tr>
              <td><%= link_to user.first_name + ' ' + user.last_name, profile_path(id: user.id), style: 'color: lime' %></td>
              <td class="greenText"><%= user.age %></td>
              <td class="greenText"><%= user.posts.length %></td>
              <td></td>
              <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }, style: 'color: lime' %></td>
            </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<%= render 'form' %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @user.age %>
</p>

<p>
  <strong>Bio:</strong>
  <%= @user.bio %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %>

<strong>Messages:</strong>
<br>


<%= link_to 'Back', users_path %>